{% set name = "tardigrade_micromorphic_tools" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: '..'

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - set -x
    # Build and install c++ libraries
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release - DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build build --target tardigrade_micromorphic_tools
    - cmake --install build --prefix ${PREFIX}
  skip: true  # [win]

requirements:
  host:
    - python
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - cython #Maybe we don't need this?
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - breathe >=4.3.0
    - clang-tools
    - doxygen
    - libboost-python-devel >=1.82
    - pip
    - python-build 
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=3.0.4
    - sphinx_rtd_theme >=0.4.3
    - sphinxcontrib-bibtex
    - eigen >=3.3.7
    - tardigrade_error_tools >=0.9.8
    - tardigrade_vector_tools >=0.8.7
    - tardigrade_constitutive_tools >=0.8.5
  run:
    - eigen >=3.3.7
    - tardigrade_error_tools >=0.7
    - tardigrade_vector_tools >=0.7
    - tardigrade_constitutive_tools >=0.7
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - libcxx        # [osx]

test:
  requires:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - clang-tools
    - libboost-python-devel >=1.82
    - doxygen
    - sphinx
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_tardigrade_micromorphic_tools.cpp
  commands:
    - mkdir build-tests
    - cd build-tests
    - cmake .. -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build . --target all --verbose
    - ctest --test-dir build --output-on-failure -R 'test_'

about:
  home: https://github.com/UCBoulder/tardigrade_micromorphic_tools/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A collection of useful tools and utilities for micromorphic continuum mechanics'
  description: |
    tardigrade_micromorphic_tools A collection of useful tools and utilities for micromorphic
    continuum mechanics. These utilities are intended to reduce the implementation time of  constitutive model
    development by providing a library of functions which are verified and ready to be implemented.
  dev_url: https://github.com/UCBoulder/tardigrade_micromorphic_tools/

